service: my-express-application

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: cn-north-1
  profile: china
  endpointType: regional

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-aws-cn-principal
